package com.lonbon.cloud.user.domain.dto;


import lombok.Data;
import com.easy.query.core.annotation.Column;
import com.lonbon.cloud.base.entity.BaseEntity;

import java.util.Map;

import lombok.Data;
import lombok.EqualsAndHashCode;
import com.lonbon.cloud.base.entity.JsonObjectTypeHandler;
import com.lonbon.cloud.user.domain.value_object.TenantConfig;

import java.io.Serial;
import java.time.OffsetDateTime;

import com.easy.query.core.annotation.Version;

import java.util.UUID;

import com.easy.query.core.basic.extension.version.VersionIntStrategy;
import com.easy.query.core.basic.extension.logicdel.LogicDeleteStrategyEnum;
import com.easy.query.core.annotation.LogicDelete;
import com.easy.query.core.annotation.UpdateIgnore;

import java.io.Serializable;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.lonbon.cloud.user.domain.entity.Tenant }
 *
 * @author ${appContext.getAuthor()}
 * @easy-query-dto schema: request
 */
@Data
public class TenantUpdateDTO {


    private String name;
    private String description;
    private String domain;
    private TenantConfig config;


}
